In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("/content/StudentsPerformance_Preprocessed.csv")

In [6]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average_score,total_score
0,Female,Group B,Bachelor'S Degree,Standard,NaN,72,72,74,72.666667,218
1,Female,Group C,Some College,Standard,Completed,69,90,88,82.333333,247
2,Female,Group B,Master'S Degree,Standard,NaN,90,95,93,92.666667,278
3,Male,Group A,Associate'S Degree,Free/Reduced,NaN,47,57,44,49.333333,148
4,Male,Group C,Some College,Standard,NaN,76,78,75,76.333333,229

In [7]:
df.dtypes

gender                          object
race/ethnicity                  object
parental level of education     object
lunch                           object
test preparation course         object
math score                       int64
reading score                    int64
writing score                    int64
average_score                  float64
total_score                      int64
dtype: object

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      358 non-null    object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
 8   average_score                1000 non-null   float64
 9   total_score                  1000 non-null   int64
dtypes: float64(1), int64(4), object(5)
memory usage: 78.3+ KB

In [9]:
df.isnull().sum()

gender                           0
race/ethnicity                   0
parental level of education      0
lunch                            0
test preparation course        642
math score                       0
reading score                    0
writing score                    0
average_score                    0
total_score                      0
dtype: int64

In [10]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average_score,total_score
995,Female,Group E,Master'S Degree,Standard,Completed,88,99,95,94.000000,282
996,Male,Group C,High School,Free/Reduced,NaN,62,55,55,57.333333,172
997,Female,Group C,High School,Free/Reduced,Completed,59,71,65,65.000000,195
998,Female,Group D,Some College,Standard,Completed,68,78,77,74.333333,223
999,Female,Group D,Some College,Free/Reduced,NaN,77,86,86,83.000000,249

In [11]:
df.describe()

       math score  reading score  writing score  average_score  total_score
count  1000.00000    1000.000000    1000.000000    1000.000000  1000.000000
mean     66.08900      69.169000      68.054000      67.770667   203.312000
std      15.16308      14.600192      15.195657      14.257326    42.771978
min       0.00000      17.000000      10.000000       9.000000    27.000000
25%      57.00000      59.000000      57.750000      58.333333   175.000000
50%      66.00000      70.000000      69.000000      68.333333   205.000000
75%      77.00000      79.000000      79.000000      77.666667   233.000000
max     100.00000     100.000000     100.000000     100.000000   300.000000

In [12]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score', 'average_score', 'total_score'],
      dtype='object')

In [13]:
categorical_cols = {
    "gender",
    "race/ethnicity",
    "parental level of education",
    "lunch",
    "test preparation course"
}

In [14]:
for col in categorical_cols:
  df[col] = df[col].str.strip().str.title()
print(df[list(categorical_cols)].head())
df['average_score'] = (
    df['math score'] +
    df['reading score'] +
    df['writing score']
) / 3
df['total_score'] = (
    df['math score'] +
    df['reading score'] +
    df['writing score']
)

  parental level of education race/ethnicity  gender         lunch  \
0           Bachelor'S Degree        Group B  Female      Standard
1                Some College        Group C  Female      Standard
2             Master'S Degree        Group B  Female      Standard
3          Associate'S Degree        Group A    Male  Free/Reduced
4                Some College        Group C    Male      Standard

  test preparation course
0                     NaN
1               Completed
2                     NaN
3                     NaN
4                     NaN

In [18]:
df.to_csv('/content/StudentsPerformance_Preprocessed.csv', index=False)